version: '3'
services:
  springvue-db:
    image: mariadb:latest
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: springuser
      MYSQL_USER: springuser
      MYSQL_PASSWORD: springuser
      MYSQL_DATABASE: spring_webapp
    ports:
      - "3307:3306"
    volumes:
      - mariadb_data:/var/lib/mysql
      - ./sql:/docker-entrypoint-initdb.d

  springvue-app:
    build: .
    ports:
      - "7070:7070"
    depends_on:
      - springvue-db

volumes:
  mariadb_data:  
